const icons = [];
    const arrayNames = [
    'em-cry',
    'em---1',
    'em-smiling_face_with_3_hearts',
    'em-slightly_smiling_face',
    'em-smiley',
    'em-slightly_frowning_face',
    'em-sneezing_face',
    'em-sob',
    'em-stuck_out_tongue',
    'em-stuck_out_tongue_closed_eyes',
    'em-stuck_out_tongue_winking_eye',
    'em-sunglasses',
    'em-thinking_face',
    'em-triumph',
    'em-upside_down_face',
    'em-zany_face',
    'em-yum',
    'em-zipper_mouth_face',
    'em-woozy_face',
    'em--1',
    'em-angry',
    'em-cold_sweat',
    'em-confounded',
    'em-disappointed',
    'em-heartpulse',
    'em-face_with_rolling_eyes',
    'em-heart',
    'em-heart_eyes',
    'em-birthday',
    'em-heartbeat',
    'em-clown_face',
    'em-dizzy_face',
    'em-face_with_hand_over_mouth',
    'em-expressionless',
    'em-facepunch',
    'em-face_vomiting',
    'em-face_with_symbols_on_mouth',
    'em-flushed',
    'em-hankey',
    'em-grimacing',
    'em-hugging_face',
    'em-i_love_you_hand_sign',
    'em-joy',
    'em-kissing_smiling_eyes',
    'em-kissing_heart',
    'em-kissing_closed_eyes',
    'em-laughing',
    'em-mask',
    'em-money_mouth_face',
    'em-no_mouth',
    'em-neutral_face',
    'em-open_mouth',
    'em-pleading_face',
    'em-point_down',
    'em-point_left',
    'em-point_right',
    'em-point_up',
    'em-point_up_2',
    'em-pray',
    'em-raised_hands',
    'em-scream',
];

arrayNames.forEach(element => {
    icons.push(`<i class="em ${element}"></i>`);
});

export default icons;
